### ISSUE TITLE
Appimage for the new version (9.0) doesn't work in ubuntu 18.04 when the previous version worked.

### ISSUE THREAD

**Issue by c6401** [nteract/archived-desktop-app#3000]
```
n6401@mi:~$ '/home/n6401/bin/nteract-0.9.0-x86_64.AppImage' 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_nterac6StaSc/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

**Comment by jkornblum** [comment]
Yes I'm getting the same error on Ubuntu as well.

**Comment by ezatterin** [comment]
+1 on Debian 9.

**Comment by BenRussert** [comment]
This is a bug in electon-builder. We can pin a prior version and build to fix. 

I did this in #3003, but I got a circle ci error that I don't get locally so the build failed.

**Comment by rgbkrk** [comment]
Does the [.deb](https://github.com/nteract/nteract/releases/download/v0.9.0/nteract_0.9.0_amd64.deb) work for folks on Ubuntu for the time being?

**Comment by BenRussert** [comment]
> Does the .deb work for folks on Ubuntu for the time being?

The deb is fine, but on nteract.io the download for linux button defaults to the broken appimage.

**Comment by rgbkrk** [comment]
Since we've got the spawnteract change in (thank you again by the way) and we've pinned electron builder, I'll make a patch release this evening.

I wonder if we could also detect that the user downloading is on a Debian variant, using the user agent and headers like we do now for detecting Mac, Windows, and Linux. Then we can default to the `.deb`.

**Comment by rgbkrk** [comment]
`v0.9.1` is now out. Give it a spin and let me know how it goes!

**Comment by BenRussert** [comment]
> v0.9.1 is now out. Give it a spin and let me know how it goes!
It works!
